AstroTask Cider PR (Audrey Lucas)
hackclub/cider pull request #17
Opened 2024-07-21 22:41 UTC by tinkeraudrey

2024-07-22 14:46 UTC, faisalsayed10 requested changes

2024-07-22 14:46 UTC, faisalsayed10 commented on submissions/AstroTask/README.md
> +Ship URL: https://app.slack.com/client/T0266FRGM/C01504DCLVD
Ship URL is incorrect

2024-07-22 14:49 UTC, faisalsayed10 commented
Hi this feels barebones and very much like a generic todo list app (which we're specifically trying to avoid). I'm not really convinced on putting this to app store, since there are a million todo list apps out there. what's something unique you're doing here? how is this app specifically helping you out that other apps couldn't have?

2024-07-22 14:53 UTC, tinkeraudrey commented on submissions/AstroTask/README.md
> +Ship URL: https://app.slack.com/client/T0266FRGM/C01504DCLVD
I had a feeling it was incorrect, and didn't completely understand since the PR instructions don't really go into detail. How can I get the correct Ship URL?

2024-07-22 14:57 UTC, faisalsayed10 commented on submissions/AstroTask/README.md
> +Ship URL: https://app.slack.com/client/T0266FRGM/C01504DCLVD
Thanks for the feedback, I'll improve it in the instructions. Ship URL is the URL you get after posting it in the #ship channel on hack club slack

2024-07-22 14:58 UTC, tinkeraudrey commented
> Hi this feels barebones and very much like a generic todo list app (which we're specifically trying to avoid). I'm not really convinced on putting this to app store, since there are a million todo list apps out there. what's something unique you're doing here? how is this app specifically helping you out that other apps couldn't have?

Thank you for the feedback! AstroTask combines the ToDo List aspect with the Pomodoro technique. This is a well known time management method based on 25-minute stretches of focused work broken by five-minute breaks. AstroTask is aimed at students, and as a high schooler myself, I know how hard it is to find apps that combine all my different needs. With AstroTask, you can have your timers and tasks in one place, to maximise efficiency and workflow!

2024-07-22 15:02 UTC, tinkeraudrey commented on submissions/AstroTask/README.md
> +Ship URL: https://app.slack.com/client/T0266FRGM/C01504DCLVD
Here is the link scrappy gave me after i shipped my project: https://scrapbook.hackclub.com/tinkeraudrey

2024-07-30 19:26 UTC, faisalsayed10 commented
Hey @tinkeraudrey, sorry but i don't think this qualifies. It feels too basic at this point and there are 100s of todo list + pomodoro apps out there.

2024-07-31 15:13 UTC, tinkeraudrey commented
> Hey @tinkeraudrey, sorry but i don't think this qualifies. It feels too basic at this point and there are 100s of todo list + pomodoro apps out there.

I’m sorry, but it was not mentioned in the website nor the instructions that there were requirements on what level of originality the app should be. To my knowledge, you submit an app and if it meets the requirements you receive a grant. I am  new to coding, so this app took a lot of time to make and I put a lot of effort in. I would hate to have to completely restart. Could you take a look at it again? If you feel that this app does not meet the requirements listed on the website, could you let me know what to add to it?

2024-07-31 19:22 UTC, faisalsayed10 commented
Have u completed student ID verification through arcade?

2024-07-31 20:22 UTC, tinkeraudrey commented
> Have u completed student ID verification through arcade?

It was a while ago, but yes.

2024-07-31 20:30 UTC, faisalsayed10 commented
Could u please send me the email of your verification or smth in my DMs

2024-08-05 19:13 UTC, tinkeraudrey commented
<img width="1470" alt="Screenshot 2024-08-05 at 3 11 35 PM" src="https://github.com/user-attachments/assets/042da22b-72ff-4973-b1cd-05fa0e3e70eb">
i sent it to you here and in slack, incase you need it there too

2024-08-05 19:14 UTC, faisalsayed10 approved these changes

2024-08-05 19:15 UTC, merged