SwimTrack
hackclub/cider pull request #20
Opened 2024-07-25 14:30 UTC by saumilthecode

preliminary review :D

2024-07-25 17:07 UTC, faisalsayed10 commented on submissions/SwimTrack/README.md
> +it is not complete yet so no ship :p (the onboarding is abit borked rn)
would love if u could fix everything, get it completed and ship it :)

2024-07-25 17:07 UTC, faisalsayed10 commented on submissions/SwimTrack/README.md
> +**Video Demo URL**: [https://youtube.com/xyz](https://www.youtube.com/gxe)
would be great if u can attach the demo link

2024-07-25 17:12 UTC, faisalsayed10 requested changes
left a review in testflight

2024-08-24 07:56 UTC, saumilthecode commented
ok so i currently cant figure tipkit out for the life of me but am open to the rest of the app being checked on first so here's the link to me running through it

https://hackclub.slack.com/files/U078K08NN2Y/F07F75Y5XFY/simulator_screen_recording_-_iphone_15_-_2024-08-04_at_09.33.37.mp4

2024-08-24 08:01 UTC, saumilthecode commented
wow managed to make the .ds_stores dissapear

2024-08-26 12:55 UTC, saumilthecode commented
Hello! @faisalsayed10 i finished up with some final changes and think this is worthy enough of the grant now :)

2024-08-28 06:33 UTC, faisalsayed10 approved these changes
great work on the updates :)

2024-08-28 06:35 UTC, merged